# not using as of now
version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"  # Map React app to port 3000
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"  # Map Node.js server to port 5000
    environment:
      - NODE_ENV=production
